### ISSUE TITLE
teres1-ledctrl consumes 100% cpu

### ISSUE THREAD

**Issue by khumarahn** [OLIMEX/DIY-LAPTOP#10]
I have another issue to submit.

Occasionally, `teres1-ledctrl` starts to consume 100% of the cpu (one core), and the leds do not work. I observed it on both the original ubuntu, and on my gentoo, where I compiled it myself.

This happens rarely, I have no idea what triggers it.

A screenshot:
![screenshot-20171108 001606](https://user-images.githubusercontent.com/5206045/32524996-5b318cc4-c41a-11e7-8e70-2157cff8ae93.png)

**Comment by khumarahn** [comment]
upd: turning the keyboard on and off as in #8 does trigger this. However, I do not remember how it happened with the stock ubuntu - I wasn't experimenting with anything this low level.

**Comment by d3v1c3nv11** [comment]
This service is temporary workaround that will fix the issue for now:
```bash
[Unit]
Description=teres1-ledctrl service stop before sleep
Before=sleep.target

[Service]
Type=oneshot
ExecStart=-/usr/bin/pkill -9 teres1-ledctrl

[Install]
WantedBy=sleep.target
```
create it with
```bash
sudo nano /etc/systemd/system/teres1-ledctrlkill.service
sudo systemctl enable teres1-ledctrlkill.service
sudo systemctl start teres1-ledctrlkill.service
```

**Comment by hehopmajieh** [comment]
I think this is a workaround , not fix.  @d3v1c3nv11  take a look  
[here](https://github.com/OLIMEX/DIY-LAPTOP/blob/master/SOFTWARE/A64-TERES/teres1-ledctrl/teres1-ledctrl.c#L82)
This will die in horrible pain, if file descriptor is missing or already opened. Simple file check will do the trick. But it needs additional debug

**Comment by khumarahn** [comment]
Yeap, it is not the right fix. I have a script (in #8) which unbinds the keyboard device when the lid is closed. There I also had to add a restart of the led control service.

Also, I do not use systemd. I would happily use it, but it requires a recent kernel. Our 3.10 is just too old, while older versions of systemd require to many patches to compile. Luckily for me, gentoo comes with openrc. It is a very good init system, but it does not manage suspend.

**Comment by khumarahn** [comment]
#13

**Comment by d3v1c3nv11** [comment]
Merged.

**Comment by khumarahn** [comment]
ok, thank you. It seems, this is done.
