### ISSUE TITLE
3D files for the plastic case

### ISSUE THREAD

**Issue by abdberkana** [OLIMEX/DIY-LAPTOP#19]
Hi all, can some one point me to the link where to download the 3D files of the enclosure ?

**Comment by DanKoloff** [comment]
We don't have such. Refer to this blog post about the plastics: https://olimex.wordpress.com/2018/01/19/teres-i-diy-open-source-hardware-modular-hackers-laptop-update/

Quote from it: "As you all know we suck at mechanical engineering and we had to find all plastic parts from Chinese laptop supplier. Some people asked about possible 3D designs of the laptop case but we are not capable to do this..."

**Comment by jcstaudt** [comment]
Closing the loop:

A 3D-printed case design has been developed by [Fork Sand, Inc.](https://github.com/forksand) and the design files may be found [here](https://github.com/forksand/olimex-teres-case).  I have added a link within this repo's [FAQ](https://github.com/OLIMEX/DIY-LAPTOP/blob/master/doc/web/res_faq.md) page.
