### ISSUE TITLE
Some questions and suggestions

### ISSUE THREAD

**Issue by uGiFarukh** [OLIMEX/DIY-LAPTOP#20]
First of all, really nice open source project. I appreciate all the efforts behind this project. So, some of my initial questions if you guys can answer:

1. Why you guys are limiting yourself to Allwinner A64 processor and only 2GB DDR3 memory? Also, why not go for M.2 SSD instead of the eMMC to reduce the overall latency of the system and increase the disk I/O? Ever though about RockChip RK3399? with ARM Cortex A72 + A53 in big.LITTLE configuration? And by the way the 64bit CPU's can support more than 2GB or RAM. So, why not a 4GB and 8GB DDR3 Dual Channel variations?

2. Why no USB 3.0/3.1 and Gigabit ethernet? Or these modules still in development? And how about WiFi AC and BLE 4.2 or 5?

3. As a kit based or modular project why not multiple chasis and lcd sizes? 10.1", 11.6", 12.3", 13.3", 15" etc.

<REDACTED BLATANT ADVERTISEMENT>

Thanks.

**Comment by DanKoloff** [comment]
Is this the suitable place for friendly talk? Does your post describe, suggest or solve an issue? Please join the forums. I've also removed the advertisement part.
