### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by dudjima** [OLIMEX/DIY-LAPTOP#22]
After two weeks. for several days, the sound no longer works. 
output jack or speaker = no sound

any idea ? try a new install with you're torrent linux mate ?

thank you

**Comment by DanKoloff** [comment]
You didn't disable it with keyboard combination by chance, nor lowered the volume to minimum, right? New install would help if it is a software issue. Refer to the user's manual, there are instructions about a clean install.

**Comment by dudjima** [comment]
it isn't disable with keyboard. i will try a new install

**Comment by jcstaudt** [comment]
@dudjima Did the new install fix your issue?

**Comment by jcstaudt** [comment]
Closing inactive issue.  @dudjima please reopen if you can elaborate.
