### ISSUE TITLE
Post assembly feedback

### ISSUE THREAD

**Issue by utilum** [OLIMEX/DIY-LAPTOP#23]
Way to go, guys!

Thank you so much. I've helped a 10 years old put the machine together in a couple of afternoons, it was a fun learning experience for both of us. And it _works as is_ !

The one glitch: No response from the touchpad. The connections are now under the glued battery, so not easily accessible. What do you suggest?

In retrospect, is it really necessary to glue the battery in? What to do if/when it needs replaing?

Keep up the good work.

**Comment by DanKoloff** [comment]
Probably one of the connectors around TERES-PCB5-KEYBOARD or TERES-PCB3-TOUCH-BTN got loose.

Remove the battery carefully. Get rid of old double-sided tape carefully - without puncturing or compromising the battery. After it is removed from the panel, clean both sides with some cloth and alcohol. Fix connectors (refer to the pictures about which side has to be up, check if they are fully inserted, etc). After everything seems according to the master plan, re-attach the battery - maybe apply new double sided tape (shouldn't be hard to find in local book store).

< In retrospect, is it really necessary to glue the battery in? What to do if/when it needs replaing?

Even in very expensive tablets and smartphones you can see tape or glue used. Sometimes it is the fastest and most secure way. While it is not pretty, it is cheap to replace. At least we couldn't think of another way to keep the battery firmly in place. We are always open to suggestions for improvement, of course. If you have any idea how to attach it let us know.

**Comment by jcstaudt** [comment]
I constructed my own DIY laptop last year using several clustered SBCs. I used pieces of Velcro (or similar brand) adhesive strips, cut to the desired size, to secure the SBCs, batteries, USB power/data hub PCBs, etc.  The adhesive used on these strips is quite strong and comes in several "strength" grades.  I was even able to place some strips on the bottom of a few SBCs and carefully removed them later on without damaging the boards.

One thing to consider, though, is that certain brands or strength grades may be constructed of thicker material; you'll have to ensure they will still fit in the enclosure without bulging the case or straining any hardware.

**Comment by utilum** [comment]
Thank you for the detailed response @DanKoloff, and the suggestion @jcstaudt , adhesive strips of Velcro or another brand are a great idea. I'll try that when I fix and post results here.

**Comment by albjeremias** [comment]
awesomeness!!! :)) just assembled mine.. as feedback the hardest part was the monitor, this wifi cable was really hard to put in place... the touchpad is not working perfectly.. has some glitches.. all the rest is so awesome! thank you guys!

**Comment by jcstaudt** [comment]
@utilum Any luck with securing the battery?

**Comment by utilum** [comment]
Frankly, I have not gotten to doing it yet, but I'm content with the solid advice I already found here, and can close the ticket if you like.

**Comment by jcstaudt** [comment]
Thank you for the update.  Best of luck with the mod!
