### ISSUE TITLE
Add design files for TERES-019-Camera

### ISSUE THREAD

**Issue by jcstaudt** [OLIMEX/DIY-LAPTOP#26]
While writing some documentation, I noticed that the design files for **TERES-019-Camera** seem to be missing.  Are they available, and if so, can we get them incorporated?

**Comment by DanKoloff** [comment]
It is a standard camera module that we purchase. The camera is not designed by Olimex. I have only one document available and I will upload it now. Maybe Tsvetan has more info about the camera module.

**Comment by jcstaudt** [comment]
That is what I thought, but it's good to ask. More info would be great if you have it. Otherwise, we can close the issue for now.
