### ISSUE TITLE
kernel PREEMPT, are there alternatives?

### ISSUE THREAD

**Issue by albjeremias** [OLIMEX/DIY-LAPTOP#27]
**Is your feature request related to a problem? Please describe.**
I feel that my teres is quite slow, using firefox... Which kind of optimizations can I do? Can i upgrade the RAM? (i dont think so, just confirming)

**Describe the solution you'd like**
I'd like to known the command to install another kernel which is not preempt, will it affect anything? is teres using grub?

i expect something like: $ sudo apt install kernel-...-non-preempt

**Describe alternatives you've considered**
Try to install it, but i might break the bootloader? Or even the cpu may not be compatible...

**Comment by jcstaudt** [comment]
Unfortunately the memory isn't expandable. Memory upgrades on the TERES are the most pressing need, and the platform has received criticism on social media for this limitation. With the overwhelming number of web apps running on practically any modern website, casual web browsing is extremely limited on any computer with <4GB of RAM. The A64 is [limited to 3GB RAM](https://linux-sunxi.org/A64) so an alternative processor would be required. The Rockchip RK3328 SoC supports **at least** 4GB, but I am not sure what its max is. It would be nice to feature standard memory interfaces and memory controllers on the TERES to allow modularity. (Are these interfaces all "open?" See the [MNT Reform](http://mntmn.com/reform/) for an idea of what I mean.)

I'm not immediately aware of an easy way to do that, but I'd be interested to know! TERES uses u-boot and not grub. For example, [here](https://wiki.debian.org/InstallingDebianOn/Olimex/Teres-I) is some information regarding a Debian installation on the TERES.

**Comment by q2dg** [comment]
Thanks for your clear explanation, @jcstaudt . Unfortunately, having only 2GB of RAM (and not being able to upgrade it) is a definitive black hole. Thanks anyway for your effort.

**Comment by jakeogh** [comment]
The RK3328 datasheet mentions it's a 32bit memory bus on page 7: http://opensource.rock-chips.com/images/d/d7/Rockchip_RK3328_Datasheet_V1.1-20170309.pdf

**Comment by Kreyren** [comment]
@q2dg Why is it a black hole? I run full GNOME and do engineering in FreeCAD on my teres without an issue O_o

**Comment by q2dg** [comment]
Well, it depends on your use cases. As @jcstaudt has said, "With the overwhelming number of web apps running on practically any modern website, casual web browsing is extremely limited on any computer with <4GB of RAM." So, well, maybe it's not your experience. Greetings.
