### ISSUE TITLE
Decision: Host .torrent files within this git repo?

### ISSUE THREAD

**Issue by jcstaudt** [OLIMEX/DIY-LAPTOP#32]
It would be useful to store all official Teres operating system image torrent files within this git repository.

Pros | Cons
:-------:|:-------:
|Ability to tag operating system releases within git and update any associated product resources (software, documentation, etc) to match the new release|Torrent files are binary files (~20-50kB) which steadily bloat the repository over time
|In-line documentation to describe "officially supported by Olimex" software and "unofficial distributions" to comprise a comprehensive directory of compatible operating systems|Initial work: the website would need to direct the "newest" link to this git repository
|Past torrents within git history, easily found via tags/releases|
|Static links to be placed for external projects, i.e. Armbian, but we wouldn't be responsible to maintain them ourselves|
|Could more easily create "newest" torrent file with symlink to most recently pushed torrent file, in order to alleviate website link updates any time a new image is released|

Alternatively, we can continue keeping all torrent files in the black/white Teres product pages and update the links when appropriate.

What are your thoughts?

**Comment by DanKoloff** [comment]
I would try to do it for future releases. I already started uploading the torrents for the official images for A20 boards here: https://github.com/OLIMEX/OLINUXINO/tree/master/SOFTWARE/A20/Official%20image%20download%20torrents

**Comment by jcstaudt** [comment]
Sounds good, we can do that. So long as we don't rename them or move them around, it shouldn't break links on external websites. Alternatively, we could always choose to link to URL-shortened links on external websites and simply re-link them if we decide to re-organize the torrent locations.

(If anyone disagrees with this decision, feel free to open this issue for further discussion.)
