### ISSUE TITLE
Don't power on the board when connected to power supply

### ISSUE THREAD

**Issue by jcstaudt** [OLIMEX/DIY-LAPTOP#34]
Currently, if the laptop is off, then connected to mains power using the barrel jack, it will power itself on. This is not ideal when, for example, the battery is very low at the end of the day and I wish to charge it overnight. I feel that the laptop should only power on (from off, not standby or hibernation) when the power button is pressed manually or if a restart command was issued.

**Comment by khumarahn** [comment]
I can't reproduce. My Teres does not turn on on power plug. But it does turn the display on for a few seconds, showing that it is charging.

**Comment by jcstaudt** [comment]
This issue is now referenced as a known issue in Olimex' WordPress blog, dated 13 February 2019: [TERES-I Open Source Hardware Laptop has new experimental Armbian Mainline Linux image for download](https://olimex.wordpress.com/2019/02/13/teres-i-open-source-hardware-laptop-has-new-experimental-armbian-mainline-linux-image-for-download/)

> Automatically turns on upon applying power via the PWR_JACK, we need time to patch mainline uboot

**Comment by khumarahn** [comment]
I can reproduce this now, with the new u-boot.
