### ISSUE TITLE
can't open PDF on macOS default reader

### ISSUE THREAD

**Issue by GETandSELECT** [OLIMEX/DIY-LAPTOP#41]
I use latest macOS and can't open PDF with default reader

```
open -a Preview DIY-LAPTOP/doc/manuals/TERES-I-rev1.4.pdf

The file “TERES-I-rev1.5.pdf” could not be opened.
It may be damaged or use a file format that Preview doesn’t recognise.
```

just a question. Why is this repo 1.2G in size? A clone/checkout takes ages.

**Comment by DanKoloff** [comment]
> Why is this repo 1.2G in size?

It contains the full sources required to compile the Linux.

> I use latest macOS and can't open PDF with default reader

We don't have any MacOS device around to test. I'd recommend checking with another PDF viewer or trying another method of opening it. You can always however get the source .ODT file instead and generate a PDF. The source was made with LibreOffice and LibreOffice can be downloaded for MacOS. So get LibreOffice and open the https://github.com/OLIMEX/DIY-LAPTOP/blob/master/doc/manuals/TERES-I-rev1.5.odt
