### ISSUE TITLE
Update the design with more efficient CPU

### ISSUE THREAD

**Issue by Kreyren** [OLIMEX/DIY-LAPTOP#45]
### Is your feature request related to a problem? Please describe.**

Got Pinebook Pro recently and i hate that:
1. I don't have KiCAD files for it to easily add functionality that i need e.g. fingerprint, hotswappable batteries, etc..
2. The RK3399 has spectre and meltdown vulnerabilities and is allegedly using proprietary blobs

### Describe the solution you'd like

My end goal is better, equal or tolerably worse alternative to Pinebook Pro that doesn't have security issues and proprietary blobs.

Can we do better with TERES-1? It's currently using the A64 which is too slow for me

### Describe alternatives you've considered

The IMX8QM-TUKHLA seems to be a good alternative to RK3399 with allegedly no blobs, but it's still not released and it seems that it's development stalled likely due to blobs..

The next best option seems to be the iMX8QuadPlus which compared to RK3399 has one less Cortex-A72, but according to https://olimex.wordpress.com/2022/01/25/imx8mplus-som-is-alive-and-boots there is an issue with supply

### Additional context

I have experience with hardware and software development and am willing to help if you can do the brainstorm on what CPU should be used.

**Comment by TsvetanUsunov** [comment]
IMX8QM processor alone is EUR 200 this is automotive grade processor and you are not correct, there is co-processor running non free firmware inside it, which takes care of all initializations of memory, etc. NXP provide SDK so you can write your own firmware, but do not have public the sources of the firmware which are used to ship the processors, which may need quite of work. 

For IMX8MQP NXP is working to mainline it, so IMO is more suitable for FOSS OSHW product.

**Comment by Kreyren** [comment]
@TsvetanUsunov In hypothetical scenario where we have the documentation needed to know how to make a board for it:

What about SnapDragon Mobile 845?
The PostmarketOS wiki says that it's fully mainlined (with partial support for modem)[[1]](https://wiki.postmarketos.org/index.php?title=Qualcomm_Snapdragon_845_(SDM845))

> For IMX8MQP NXP is working to mainline it, so IMO is more suitable for FOSS OSHW product. -- @TsvetanUsunov (https://github.com/OLIMEX/DIY-LAPTOP/issues/45#issuecomment-1232610184)

Because like that only adds ~0.3 GHz in comparison to A64

**Comment by Kreyren** [comment]
Found RK3588S for which the datasheet is widely available and seems like a good option considering budget and resource efficiency.

In terms of mainlining, the work seems to be ongoing in 6.1 -- https://gitlab.collabora.com/hardware-enablement/rockchip-3588/notes-for-rockchip-3588/-/blob/main/mainline-status.md

CC @TsvetanUsunov

Update: As discussed it's better to wait for the TUKHLA

**Comment by Kreyren** [comment]
@TsvetanUsunov What about StarFive JH7110?

Relevant: https://github.com/starfive-tech/VisionFive2/issues/39

AllWinner A64 compared to StarFive JH7110:
* CPU:
	* AllWinner A64
		* Quad-Core ARM Cortex-A53 @ up to 1.2 Ghz
	* StarFive JH7110
		* Quad-core 64-bit RISC-V SiFive U74 (RV64GC) processor @ up to 1.5 GHz with 32KB D-Cache, 32KB I-cache
		* Single-core 64-bit RISC-V SiFive S7 (RV64IMAC) monitor core with 16KB I-cache, 8KB DTIM
		* Single-core 32-bit RISC-V SiFive E24 (RV32IMFC) real-time control core with 16KB I-cache
		* Up to 2MB L2 cache
* RAM: 2GB DDR3L -> 8GB LPDDR4
* Architecture: aarch64 -> riscv
* Lithography: 40nm -> 28nm
* GPU: Mali 400 MP2 -> Imagination BXE-4-32 

Info on the GPU driver for linux mainline: https://developer.imaginationtech.com/open-source-gpu-driver/

:warning:  Seems to have binary blobs for the GPU (https://gitlab.freedesktop.org/frankbinns/linux-firmware/-/tree/powervr/powervr)

.. i guess not suitable if/until the GPU firmware is handled?

**Comment by Kreyren** [comment]
Considered `won't fix`
