### ISSUE TITLE
Kernel changes - Mainline

### ISSUE THREAD

**Issue by andir** [OLIMEX/DIY-LAPTOP#5]
First let me say, that I am grateful that people are working on this! Thank you!

Are you planning on contributing the changes to the kernel sources into the upstream linux kernel?

In my opinion (and that of many others) a product that only runs on a (soon) ancient linux kernel with a custom patchset is not a product we would buy.

In the past there have been way too many ARM board (that look nice at a good price point) but lack proper mainline support…

**Comment by bibor** [comment]
The sunxi comunity is working on A64 mainline support.
The results are documented here (not always up-to date)https://linux-sunxi.org/Linux_mainlining_effort https://linux-sunxi.org/A64

**Comment by zavorka** [comment]
[Soon](https://lkml.org/lkml/2018/4/30/288).
