### ISSUE TITLE
Troubleshooting link is broken in README

### ISSUE THREAD

**Issue by xloem** [OLIMEX/DIY-LAPTOP#51]
Just a note regarding this repository.

**Comment by DanKoloff** [comment]
link to README in question?

**Comment by xloem** [comment]
https://github.com/OLIMEX/DIY-LAPTOP#other-resources
https://github.com/OLIMEX/DIY-LAPTOP/tree/master#other-resources

**Comment by jcstaudt** [comment]
Fixed on the `rel3` branch in commit 6f9910d. Thkanks so much @xloem for letting us know!

**Comment by xloem** [comment]
Thanks. It looks like the original plan was to have documentation for diagnosing issues. It’s too bad we didn’t all make this happen, me included.

**Comment by jcstaudt** [comment]
Agreed. Yes, you're right; my initial plan was to browse the most common or annoying hurdles seen in the forums and attempt to aggregate them into some organized structure which would resemble an operator's manual. I'm a bit limited in my free time lately to do this entirely on my own, but I'm happy to assist if you're willing to help or if there's an expressed need from the community.
