### ISSUE TITLE
Add resettable fuse for 5VDC3A on the Vin

### ISSUE THREAD

**Issue by Kreyren** [OLIMEX/DIY-LAPTOP#61]
Referencing https://www.olimex.com/forum/index.php?topic=7782.0

Proposing to integrate **resettable fuse** for 5VDC3A on the Vin

Options: https://eu.mouser.com/c/circuit-protection/thermistors/resettable-fuses-pptc/?current%20rating%20-%20max=3%20A&maximum%20voltage=5%20V

So that if the user overvoltages the laptop it won't damage anything

**Comment by DanKoloff** [comment]
I don't we would place fuse by default. We have provided the option to add fuse, user can cut between the pads of FUSE2 and add such there. Refer to the picture below

![teresfuse2](https://user-images.githubusercontent.com/6028552/229439946-e641c4b5-b942-47c9-b928-f896d182fb74.png)

**Comment by Kreyren** [comment]
@DanKoloff i think you missunderstod, the proposed fuse (e.g. https://eu.mouser.com/ProductDetail/onsemi/NIV6350MT2TXG?qs=xZ%2FP%252Ba9zWqa2xJAD3VNXxQ%3D%3D) seems to be a 0.659 EUR integrated circuit component that automatically cuts power when it goes past the 5VDC3A otherwise it lets power go through, the reset can be handled by the fuse itself without the need of user doing anything instead of the common fuse that blows itself and has to be replaced when the designed current passes set value.

So FUSE2 is not an option without e.g. developing a daughter board on top of it as the pining is not compatible:

![](https://i.imgur.com/wSDDJbF.png)


Example use from datasheet:
![](https://i.imgur.com/1Sk3G43.png)

**Comment by Kreyren** [comment]
@DanKoloff Did you read the reply?

**Comment by xloem** [comment]
Noting it sounds like olimex does not want to add a fuse, but aren’t there 2-lead resettable fuses? What is the advantage of an entire integrated chip?

It would be super nice to have a fuse there by default, prevent board damage.

**Comment by TsvetanUsunov** [comment]
I do wonder why additional fuse is necessary if the power is supplied with Adapter which already have all the protections?

**Comment by xloem** [comment]
Some of us prefer to power the laptop with DC. https://linux-sunxi.org/Olimex_Teres-A64#Cut_the_power_cable
I saw the same topic somewhere else on cutting the power cable, not certain where.

**Comment by khumarahn** [comment]
I cannot use the stock power adapter for teres: it only fits the European power socket, it is bulky, and I travel quite a lot. I use instead a usb cable and charge from various usb chargers.

I never had any problems with this, but I don't think that it is safe to rely on protections of the power adapter.

**Comment by Kreyren** [comment]
> Some of us prefer to power the laptop with DC. https://linux-sunxi.org/Olimex_Teres-A64#Cut_the_power_cable I saw the same topic somewhere else on cutting the power cable, not certain where. -- @xloem (https://github.com/OLIMEX/DIY-LAPTOP/issues/61#issuecomment-2154824652)

It's me who wrote that there as i basically charge the laptop from any kind of power source that i can find.. e.g. i often splice the cables together with WAGO connectors to charge in the car, friend's phone, escooter or even stuff like disassmbling street light and connecting aligator clips to the power there to charge it (.. when really desperate and the situation needs it..)

Afaik other teres users do the same just usually not as extreme e.g. charging from a portable solar panel is apparently very common which afaik has an increased risk for spikes in voltage/current.

also as said in https://github.com/OLIMEX/DIY-LAPTOP/issues/67 the stock adapter is useless shit.

FWIW also currently working on a standard to get a screwable connectors e.g.  YC8 (https://www.youtube.com/watch?v=stdiyrQk3VU) to deprecate the need for WAGOs in my teres development, but i am struggling to figure out how to make them water-proof and non-annoying to use.

**Comment by Kreyren** [comment]
Additionally: Not completed and moved in https://git.dotya.ml/KREYLIMEX/TERES/issues/23

**Comment by xloem** [comment]
I would connect a 5v buck/boost regulator to any solar panel. Surprised it would work without.
