### ISSUE TITLE
[REQUEST] Open-Source the list of compatible DRAM modules for the A64

### ISSUE THREAD

**Issue by Kreyren** [OLIMEX/DIY-LAPTOP#71]
Referencing: https://git.dotya.ml/KREYLIMEX/Teres/issues/12

The OLIMEX OlinuXino-A64's schematics have a note:

![image](https://github.com/OLIMEX/DIY-LAPTOP/assets/11302521/25d97911-5c35-4ca1-b96c-d4b6f3c30bd3)

Requesting to open-source this list to make mainboard adjustments easier and more economical.

**Comment by TsvetanUsunov** [comment]
what do you mean by open source this list? changing the DDR usually includes tuning of the DRAM controller parameters, if you want you can experiment with any other DDRs just have to run tests and see the optimal parameters which to load to the DRAM controller, the memories are not so easy to exchange like the resistors

**Comment by Kreyren** [comment]
> what do you mean by open source this list? -- @TsvetanUsunov (https://github.com/OLIMEX/DIY-LAPTOP/issues/71#issuecomment-2154728034)

pineppl said that allwinner provides them with a list of modules that the manufacturer tested and has useful notes for, so that when people are manufacturing the design themselves to be able to pick the available module or be able to do 3GB RAM + for custom A64-based designs e.g. i wanted to have a A64 SOM to make a PCBs for a 3D printer.

> changing the DDR usually includes tuning of the DRAM controller parameters, if you want you can experiment with any other DDRs just have to run tests and see the optimal parameters which to load to the DRAM controller, the memories are not so easy to exchange like the resistors -- @TsvetanUsunov (https://github.com/OLIMEX/DIY-LAPTOP/issues/71#issuecomment-2154728034)

It would require making some kind of management to be able to easily change the module as the pin layout and routing often changes, if you have any relevant data on the subject it might help some users who were modding the design.
